// src/component/Table.tsx
import React from 'react';

export interface TableProp{
  data: (number|string) [][]
}


export default function Table(props:TableProp) {
    const data = props.data;
    const listItems = data.map((row, rowIndex) => 
      <tr key={rowIndex.toString()}>
        {row.map((column, columnIndex)=>
        <td key={columnIndex}>{column}</td>
      )}
      </tr>
    );
    return (
      <div>
        <h2>React</h2>
        <table>
          <tbody>
          {listItems}
          </tbody>
        </table>
      </div>
    );
  }

// src/component/Table.svelte
<script lang="ts">
    export let data: (number|string) [][] = [[],[],[]];
</script>

<h2>Svelte</h2>
<table>
    <tbody>
        {#each data as row, rowIndex}
        <tr>
            {#each row as cell, columnIndex }
                <td>{cell}</td>
            {/each}
        </tr>
        {/each}
    </tbody>
</table>
