// src/component/Table.tsx
import React from 'react';

export interface TableProp{
  data: (number|string) [][]
}


export default function Table(props:TableProp) {
    const data = props.data;
    const listItems = data.map((row, rowIndex) => 
      <tr key={rowIndex.toString()}>
        {row.map((column, columnIndex)=>
        <td key={columnIndex}>{column}</td>
      )}
      </tr>
    );
    return (
      <div>
        <h2>React</h2>
        <table>
          <tbody>
          {listItems}
          </tbody>
        </table>
      </div>
    );
  }

// src/component/Table.vue
<script lang="ts">

export default {
    props: {
        data:{
            default: ()=>{ [[], [], []] }
        }
    }
};

</script>

<template>
<div>
    <h2>Vue</h2>
    <table>
        <tbody>
            <tr v-for="row in data" :key="row" bind:data>
            <td v-for="column of row" :key="column">{{column}}</td>
            </tr>
        </tbody>
    </table>
</div>
</template>
